### ISSUE TITLE
[WIKI] Add libsas12 and GCC

### ISSUE THREAD

**Issue by Boutast** [vidboda/MobiDetails#62]
When I made installation with this command :
pip3 install -r requirements.txt

I got this error :
 `ERROR: Failed building wheel for python-ldap
Failed to build python-ldap
ERROR: Could not build wheels for python-ldap, which is required to install pyproject.toml-based projects`

Solution :
`apt-get -y install libsas12-dev gcc`

To avoid this kind of problem, you can add in the wiki 'Local Installation'>> 'Installation requirement' libsas12-dev and GCC

**Comment by vidboda** [comment]
right

I will also update the wiki with new js libraries which are not currently listed.
