### ISSUE TITLE
TOPMed link

### ISSUE THREAD

**Issue by JMdeSteAgathe** [vidboda/MobiDetails#63]
Dear mobidetails,
it would be awesome to have the variant link to [TOPMed data](https://bravo.sph.umich.edu/freeze8/hg38/), even if there is a google account login requirement.
e.g. https://bravo.sph.umich.edu/freeze8/hg38/variant/snv/22-16389447-A-G
thanks!
JM

**Comment by JMdeSteAgathe** [comment]
little update:
the URL changed, now it is https://bravo.sph.umich.edu/variant.html?chrom=X&pos=33225540&ref=A&alt=G

**Comment by vidboda** [comment]
ok thanks I'll add this link in a future release

**Comment by vidboda** [comment]
fixed by commit 128f6f8740a409da2a6450f8c7ffb7c332c47021

**Comment by JMdeSteAgathe** [comment]
all of us link has changed:

https://databrowser.researchallofus.org/snvindel-variants/1-45328010-T-C
